### ISSUE TITLE
Snap for Linux

### ISSUE THREAD

**Issue by yasharya2901** [aramg/droidcam#95] opened 2020-09-03 02:27 UTC
**Describe the feature you'd like to see added to the app**
I would like to have a GUI installer for Linux so that new users should not have to go around typing complex commands to set up their DroidCam. At least, having a snap package would be enough.

**Comment by aramg** [comment] 2020-09-09 03:32
Since you edited the issue, I'm closing it as a duplicate of #92 and #49 .
As far as a better GUI with video preview: #38

**Closed by aramg** 2020-09-09 03:32 UTC
