### ISSUE TITLE
could not found device v42loopback : error after updating ubuntu

### ISSUE THREAD

**Issue by NixonNelson** [aramg/droidcam#20] opened 2020-02-27 13:36 UTC
I dont know why but the v42loopback device is removed somehow after updating my ubuntu .
when i try to start  droidcam client ,it gives me error
>device not found(/dev/video[0-9]).
>did you install it?

After reinstalling the client it works.

**Comment by morsik** [comment] 2020-03-18 11:20
Updating Ubuntu caused updating Kernel - you must rebuild kernel module to work. This is not a bug ;)

**Comment by aramg** [comment] 2020-03-18 17:09
I guess the solution is distribute the client via the various package managers, unfortunately totally out of scope given the amount of free time I have

**Closed** 2020-03-18 17:13 UTC
